include ../../../build/common-env.mk
include ../../build/common-flags.mk

KM_NAME := ext
RUST_CRATE_NAME := ext
RUST_MODULE_DIR := $(CURDIR)
include $(PROJECT_ROOT)/modules/build/rust-module.mk
MAKEFLAGS += -rR --no-print-directory
