//! Generates per-IP register constant modules from the Linux amdgpu
//! `asic_reg` headers (register offsets and field shift/mask constants).
//!
//! The Linux source tree is located via the `LINUX_SRC_DIR` environment
//! variable (set by the GNUmakefile; defaults to `../../../../../../linux`
//! relative to this crate, i.e. the sibling of the naos tree).

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

struct IpHeader {
    /// Rust module name under `regs`.
    module: &'static str,
    /// Directory under `drivers/gpu/drm/amd/include/asic_reg`.
    dir: &'static str,
    /// Header file base name (e.g. `gc_10_3_0`).
    base: &'static str,
}

const HEADERS: &[IpHeader] = &[
    IpHeader {
        module: "gc10_3_0",
        dir: "gc",
        base: "gc_10_3_0",
    },
    IpHeader {
        module: "nbio4_3_0",
        dir: "nbio",
        base: "nbio_4_3_0",
    },
    IpHeader {
        module: "nbio2_3",
        dir: "nbio",
        base: "nbio_2_3",
    },
    IpHeader {
        module: "mp13_0_2",
        dir: "mp",
        base: "mp_13_0_2",
    },
    IpHeader {
        module: "osssys6_0_0",
        dir: "oss",
        base: "osssys_6_0_0",
    },
    IpHeader {
        module: "mmhub2_0_0",
        dir: "mmhub",
        base: "mmhub_2_0_0",
    },
    IpHeader {
        module: "vcn3_0_0",
        dir: "vcn",
        base: "vcn_3_0_0",
    },
    IpHeader {
        module: "smuio11_0_0",
        dir: "smuio",
        base: "smuio_11_0_0",
    },
    IpHeader {
        module: "smuio11_0_6",
        dir: "smuio",
        base: "smuio_11_0_6",
    },
    IpHeader {
        module: "thm11_0_2",
        dir: "thm",
        base: "thm_11_0_2",
    },
    IpHeader {
        module: "hdp5_0_0",
        dir: "hdp",
        base: "hdp_5_0_0",
    },
    IpHeader {
        module: "dcn3_0_2",
        dir: "dcn",
        base: "dcn_3_0_2",
    },
    IpHeader {
        module: "dpcs3_0_0",
        dir: "dpcs",
        base: "dpcs_3_0_0",
    },
];

/// Headers that also ship a `_default.h` register-value header.
const WITH_DEFAULTS: &[&str] = &["gc_10_3_0", "mmhub_2_0_0"];

fn parse_value(raw: &str) -> Option<u64> {
    let raw = raw.trim().trim_end_matches(['u', 'U', 'l', 'L']);
    if let Some(hex) = raw.strip_prefix("0x") {
        u64::from_str_radix(hex, 16).ok()
    } else {
        raw.parse().ok()
    }
}

/// Extracts `#define NAME VALUE` pairs; the first definition wins
/// (mirrors the `#ifndef` guards used in the headers). Accepts both
/// register names (`mm`/`reg` prefixed) and field constants
/// (`REGISTER__FIELD__SHIFT` / `REGISTER__FIELD_MASK`).
fn parse_defines(text: &str) -> BTreeMap<String, u64> {
    let mut defines = BTreeMap::new();
    for line in text.lines() {
        let Some(rest) = line.trim().strip_prefix("#define ") else {
            continue;
        };
        let mut parts = rest.split_whitespace();
        let (Some(name), Some(value)) = (parts.next(), parts.next()) else {
            continue;
        };
        let is_register = name.starts_with("mm") || name.starts_with("reg");
        let is_field = name.ends_with("__SHIFT") || name.ends_with("_MASK");
        if !is_register && !is_field {
            continue;
        }
        let Some(value) = parse_value(value) else {
            continue;
        };
        defines.entry(name.to_owned()).or_insert(value);
    }
    defines
}

fn emit_module(defines: &BTreeMap<String, u64>, source: &Path, ty: &str, kind: &str) -> String {
    let mut out = String::with_capacity(defines.len() * 32 + 128);
    out.push_str("// AUTO-GENERATED by astra build.rs from ");
    out.push_str(&source.display().to_string());
    out.push_str("\n// Do not edit.\n");
    for (name, value) in defines {
        if ty == "u32" && *value > u32::MAX as u64 {
            // Absolute-address form defines (e.g. cfgBIF_* MSI masks) are
            // not dword register offsets — skip them.
            continue;
        }
        let _ = writeln!(out, "pub const {name}: {ty} = {value};");
    }
    // Offset modules additionally expose a base-address-index lookup so
    // callers resolve `<reg>_BASE_IDX` without hand-maintained tables.
    if kind == "offset" {
        let _ = writeln!(out, "#[allow(dead_code)]");
        let _ = writeln!(out, "pub fn base_idx(name: &str) -> usize {{");
        let _ = writeln!(out, "    match name {{");
        let mut arms = 0;
        for (name, value) in defines {
            if let Some(reg) = name.strip_suffix("_BASE_IDX") {
                if *value != 0 && defines.contains_key(reg) {
                    let _ = writeln!(out, "        \"{reg}\" => {value},");
                    arms += 1;
                }
            }
        }
        if arms == 0 {
            let _ = writeln!(out, "        _ => 0,");
        } else {
            let _ = writeln!(out, "        _ => 0,");
        }
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "}}");
    }
    out
}

/// Removes C/C++ comments before parsing numeric array initializers.  In
/// particular, clearstate_gfx10.h uses comments such as
/// `PA_SC_VPORT_SCISSOR_15_BR`; treating those embedded digits as initializer
/// values corrupts the packet stream generated from the array.
fn strip_c_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut chars = text.chars().peekable();
    while let Some(ch) = chars.next() {
        if ch != '/' {
            out.push(ch);
            continue;
        }
        match chars.peek().copied() {
            Some('/') => {
                chars.next();
                for comment in chars.by_ref() {
                    if comment == '\n' {
                        out.push('\n');
                        break;
                    }
                }
            }
            Some('*') => {
                chars.next();
                let mut previous = '\0';
                for comment in chars.by_ref() {
                    if previous == '*' && comment == '/' {
                        break;
                    }
                    previous = comment;
                }
            }
            _ => out.push(ch),
        }
    }
    out
}

/// Extracts `static const unsigned int NAME[] = { ... };` and
/// `static const u32 NAME[] = { ... };` data arrays, possibly spanning
/// multiple lines (used for the gfx10 clear-state and cleaner shader blobs).
fn parse_arrays(text: &str) -> BTreeMap<String, Vec<u64>> {
    let mut arrays = BTreeMap::new();
    let lines: Vec<&str> = text.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();
        if !line.contains("static const")
            || !(line.contains("unsigned int") || line.contains(" u32 "))
        {
            i += 1;
            continue;
        }
        // Name = the identifier right before '['.
        let Some(bracket) = line.find('[') else {
            i += 1;
            continue;
        };
        let name = line[..bracket]
            .rsplit(|c: char| !c.is_ascii_alphanumeric() && c != '_')
            .next()
            .unwrap_or("")
            .trim()
            .to_string();
        if name.is_empty()
            || !name
                .chars()
                .next()
                .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        {
            i += 1;
            continue;
        }
        // Gather the array body: from the first '{' to the line ending
        // with "};" (or the closing '}').
        let mut body = String::new();
        let mut found_open = line.find('{').is_some();
        while i < lines.len() {
            let current = lines[i];
            body.push_str(current);
            body.push('\n');
            if found_open && (current.trim_end().ends_with("};") || current.contains('}')) {
                break;
            }
            if current.contains('{') {
                found_open = true;
            }
            i += 1;
        }
        let Some(open) = body.find('{') else {
            i += 1;
            continue;
        };
        let Some(close) = body[open + 1..].rfind('}') else {
            i += 1;
            continue;
        };
        let tokens = strip_c_comments(&body[open + 1..open + 1 + close]);
        let values: Vec<u64> = tokens
            .split(',')
            .filter_map(|token| parse_value(token.trim()))
            .collect();
        if !values.is_empty() {
            arrays.insert(name, values);
        }
        i += 1;
    }
    arrays
}

fn emit_arrays(arrays: &BTreeMap<String, Vec<u64>>, source: &Path) -> String {
    let mut out = String::with_capacity(arrays.values().map(|v| v.len() * 12).sum::<usize>() + 128);
    out.push_str("// AUTO-GENERATED by astra build.rs from ");
    out.push_str(&source.display().to_string());
    out.push_str("\n// Do not edit.\n");
    for (name, values) in arrays {
        let _ = writeln!(out, "pub const {name}: [u32; {}] = [", values.len());
        for chunk in values.chunks(8) {
            let _ = writeln!(
                out,
                "    {},",
                chunk
                    .iter()
                    .map(|v| format!("{v}"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        let _ = writeln!(out, "];");
    }
    out
}

fn main() {
    println!("cargo:rerun-if-env-changed=LINUX_SRC_DIR");

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let linux = match env::var("LINUX_SRC_DIR") {
        Ok(dir) => PathBuf::from(dir),
        Err(_) => manifest.join("../../../../../../linux"),
    };
    let asic_reg = linux.join("drivers/gpu/drm/amd/include/asic_reg");
    if !asic_reg.is_dir() {
        panic!(
            "astra build.rs: cannot find Linux amdgpu asic_reg headers at {}\n\
             Set LINUX_SRC_DIR to a Linux source tree (>= 7.2).",
            asic_reg.display()
        );
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let mut mod_file = String::from("// AUTO-GENERATED by astra build.rs. Do not edit.\n");
    for header in HEADERS {
        let mut includes = String::new();
        let kinds: &[(&str, &str)] = if WITH_DEFAULTS.contains(&header.base) {
            &[("offset", "u32"), ("sh_mask", "u64"), ("default", "u32")]
        } else {
            &[("offset", "u32"), ("sh_mask", "u64")]
        };
        for &(kind, ty) in kinds {
            let path = asic_reg
                .join(header.dir)
                .join(format!("{}_{}.h", header.base, kind));
            let text = fs::read_to_string(&path).unwrap_or_else(|error| {
                panic!("astra build.rs: cannot read {}: {}", path.display(), error)
            });
            println!("cargo:rerun-if-changed={}", path.display());
            let defines = parse_defines(&text);
            let file_name = format!("{}_{}.rs", header.base, kind);
            fs::write(
                out_dir.join(&file_name),
                emit_module(&defines, &path, ty, kind),
            )
            .unwrap();
            includes.push_str(&format!(
                "include!(concat!(env!(\"OUT_DIR\"), \"/{}\"));\n",
                file_name
            ));
        }
        mod_file.push_str(&format!(
            "#[allow(dead_code, non_upper_case_globals, clippy::all)]\npub mod {} {{\n{}}}\n",
            header.module, includes
        ));
    }
    fs::write(out_dir.join("astra_regs_mod.rs"), mod_file).unwrap();

    // gfx10 clear-state and cleaner-shader data arrays.
    let amdgpu_dir = linux.join("drivers/gpu/drm/amd/amdgpu");
    for (name, out_name) in [
        ("clearstate_gfx10.h", "gfx10_clearstate.rs"),
        ("gfx_v10_0_cleaner_shader.h", "gfx10_cleaner_shader.rs"),
    ] {
        let path = amdgpu_dir.join(name);
        let text = fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!("astra build.rs: cannot read {}: {}", path.display(), error)
        });
        println!("cargo:rerun-if-changed={}", path.display());
        let arrays = parse_arrays(&text);
        fs::write(out_dir.join(out_name), emit_arrays(&arrays, &path)).unwrap();
    }
}
